name: TurfWarsCompanion
version: 1.0.0-SNAPSHOT
main: com.ronlab.turfwars.TurfWarsCompanion
api-version: '26.2'
dependencies:
  server:
    RonlabGameAssistant:
      required: true
      join-classpath: true
