name: TurfWarsCompanion
version: 1.0.0-SNAPSHOT
main: com.ronlab.turfwars.TurfWarsCompanion
api-version: "26.2"
dependencies:
  server:
    RonlabGameAssistant:
      load: BEFORE
      required: true
commands:
  turfwars:
    description: TurfWars developer QA test command
    permission: turfwars.admin
    aliases: [tw]
